import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function createTextPreviewPdf({ title, body }) {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  page.drawRectangle({
    x: 36,
    y: 36,
    width: 523.28,
    height: 769.89,
    color: rgb(1, 1, 1)
  });

  page.drawText(title || "HWPX Preview", {
    x: 48,
    y: 790,
    size: 18,
    font: bold,
    color: rgb(0.12, 0.1, 0.08)
  });

  page.drawText("Text-only preview generated by the local hwpx-cli bridge", {
    x: 48,
    y: 770,
    size: 10,
    font,
    color: rgb(0.42, 0.36, 0.3)
  });

  const lines = wrapText(body || "문서에서 텍스트를 읽지 못했다.", 86);
  let y = 740;
  lines.slice(0, 50).forEach((line) => {
    page.drawText(line, {
      x: 48,
      y,
      size: 11,
      font,
      color: rgb(0.16, 0.13, 0.1)
    });
    y -= 13.5;
  });

  return Buffer.from(await pdfDoc.save());
}

function wrapText(text, maxChars) {
  const normalized = String(text).replace(/\r/g, "");
  const rawLines = normalized.split("\n");
  const lines = [];

  rawLines.forEach((rawLine) => {
    if (!rawLine) {
      lines.push(" ");
      return;
    }

    let current = "";
    for (const char of Array.from(rawLine)) {
      const next = current + char;
      if (next.length <= maxChars || current.length === 0) {
        current = next;
      } else {
        lines.push(current);
        current = char;
      }
    }

    if (current) {
      lines.push(current);
    }
  });

  return lines;
}
